name:                day1
version:             0.1.0.0
github:              "szlepermarcin/aoc-2021"
license:             BSD3
author:              "Marcin Szleper"
maintainer:          "marcin.szleper@gmail.com"
copyright:           "2021 Marcin Szleper"

extra-source-files:
- README.md
- ChangeLog.md
- input.txt

description:         Please see the README on GitHub at <https://github.com/szlepermarcin/aoc-2021/tree/master/day1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day1
