name:                aoc2021
version:             0.1.0.0
github:              "szlepermarcin/aoc2021"
license:             BSD3
author:              "Marcin Szleper"
maintainer:          "marcin.szleper@gmail.com"
copyright:           "Copyright (c) 2021 Marcin Szleper"

extra-source-files:
- README.md
- ChangeLog.md
- day1.txt
- day2.txt

description:         Please see the README on GitHub at <https://github.com/szlepermarcin/aoc2021#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aoc2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2021
